/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Admin
 */
public class Generator extends javax.swing.JFrame {

    static int scaleH = 0;
    static int scaleW = 0;
    static int numberOfDone = 0;
    static String dirpath = "";
    static int numberOfIt = 4;

    /**
     * Creates new form Generator
     */
    public Generator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        numberLabel = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        testLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generations");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        prevButton.setFont(new java.awt.Font("Open Sans", 1, 11)); // NOI18N
        prevButton.setText("Previous");
        prevButton.setForeground(new java.awt.Color(230, 126, 34));
        prevButton.setBackground(new java.awt.Color(52, 73, 94));
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("Open Sans", 1, 11)); // NOI18N
        nextButton.setText("Next");
        nextButton.setBackground(new java.awt.Color(52, 73, 94));
        nextButton.setForeground(new java.awt.Color(230, 126, 34));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        openButton.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        openButton.setText("Open Folder");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        numberLabel.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        numberLabel.setForeground(new java.awt.Color(255, 255, 255));
        numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberLabel.setText("0");

        imagePanel.setBackground(new java.awt.Color(44, 62, 80));
        imagePanel.setMaximumSize(new java.awt.Dimension(550, 550));
        imagePanel.setMinimumSize(new java.awt.Dimension(550, 550));

        testLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
                imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(testLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
                imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagePanelLayout.createSequentialGroup()
                                .addComponent(testLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(openButton))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(137, 137, 137)
                                                .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 127, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numberLabel)
                                        .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openButton)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:

        if (numberOfIt > numberOfDone) {

            String nr = String.valueOf(numberOfDone + 1);

            if ((new File(dirpath + "\\" + nr + ".png").exists())) {
                ImageIcon icon = new ImageIcon(dirpath + "\\" + nr + ".png");
                System.out.println(dirpath + "\\" + nr + ".png");
                icon = new ImageIcon(scaleIcon(scaleW, scaleH, icon));
                testLabel.setIcon(icon);

                prevButton.setText("Previous");

                numberOfDone++;
                numberLabel.setText(String.valueOf(numberOfDone));

                if (numberOfIt <= numberOfDone) {
                    nextButton.setText("End");
                }
                System.out.println(numberOfDone);

            } else {
                ErrorForm errorForm = new ErrorForm();
                errorForm.NewScreen("Error, file doesnt exists");
                nextButton.setText("Error");
                prevButton.setText("Error");
            }
        } else {
            System.out.println("koniec");
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // TODO add your handling code here:
        if (numberOfDone - 1 > 0) {

            String nr = String.valueOf(numberOfDone - 1);

            if ((new File(dirpath + "\\" + nr + ".png").exists())) {

                ImageIcon icon = new ImageIcon(dirpath + "\\" + nr + ".png");
                System.out.println(dirpath + "\\" + nr + ".png");
                icon = new ImageIcon(scaleIcon(scaleW, scaleH, icon));
                testLabel.setIcon(icon);

                // prevButton.setText("Previous");
                if (numberOfDone == numberOfIt) {
                    nextButton.setText("Next");
                }

                numberOfDone--;
                numberLabel.setText(String.valueOf(numberOfDone));

                if (numberOfDone - 1 == 0) {
                    prevButton.setText("End");
                }

                System.out.println(numberOfDone);

            } else {
                ErrorForm errorForm = new ErrorForm();
                errorForm.NewScreen("Error, file doesnt exists");
                nextButton.setText("Error");
                prevButton.setText("Error");
            }

        } else {
            System.out.println("poczatek");
        }

    }//GEN-LAST:event_prevButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open(new File(dirpath));
        } catch (IOException ex) {
            Logger.getLogger(Generator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_openButtonActionPerformed



    private static Image scaleIcon(int scaleW, int scaleH, ImageIcon icon) {
        Image image = icon.getImage();
        Image newImg = image.getScaledInstance(scaleW, scaleH, java.awt.Image.SCALE_SMOOTH);
        return newImg;
    }

    private static void loadAtFirst() {
        //       String dirpath = "G:\\Studia Bartek\\Projekt-Java\\src\\Testy";
//        int numberOfIt = 2;

        if ((new File(dirpath + "\\1.png").exists())) {

            prevButton.setText("End");
            if (numberOfIt == 1) {
                nextButton.setText("End");
            }

            ImageIcon icon = new ImageIcon(dirpath + "\\1.png");

            int jHeight = imagePanel.getHeight();
            int jWidth = imagePanel.getWidth();
            int imgHeight = icon.getIconHeight();
            int imgWidth = icon.getIconWidth();

            double sizeH = 0;
            double sizeW = 0;
            double scale = 0;

            sizeH = Double.valueOf(jHeight) / Double.valueOf(imgHeight);
            sizeW = Double.valueOf(jWidth) / Double.valueOf(imgWidth);

            if (sizeH > sizeW) {
                scale = sizeW;
            } else {
                scale = sizeH;
            }
            scaleH = (int) Math.round(scale * imgHeight);
            scaleW = (int) Math.round(scale * imgWidth);
            // pierwszy obrazek wyswietlany

            icon = new ImageIcon(scaleIcon(scaleW, scaleH, icon));
            testLabel.setIcon(icon);
            numberOfDone = 1;
            numberLabel.setText(String.valueOf(numberOfDone));
            System.out.println(imagePanel.getSize().toString() + " as " + imgHeight + " " + imgWidth + "= " + sizeH + " " + sizeW + " = " + scale + " " + (int) Math.round(scale) + "x " + (int) Math.round(scale * imgHeight) + "x " + (int) Math.round(scale * imgWidth));

        } else {
            ErrorForm errorForm = new ErrorForm();
            errorForm.NewScreen("Error, file doesnt exists");
            nextButton.setText("Error");
            prevButton.setText("Error");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void Generate( String dir, int number) { //dirpath numberOfIt
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });

        dirpath = dir;
        numberOfIt = number;
        // dirpath = "G:\\Studia Bartek\\Projekt-Java\\src\\Testy";
        new Generator().setVisible(true);
        loadAtFirst();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JButton nextButton;
    private static javax.swing.JLabel numberLabel;
    private javax.swing.JButton openButton;
    private static javax.swing.JButton prevButton;
    private static javax.swing.JLabel testLabel;
    // End of variables declaration//GEN-END:variables
}
