/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Admin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    String filename = null;
    String savename = null;
    int setIterations = -1;

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        openPathField = new javax.swing.JTextField();
        savePathField = new javax.swing.JTextField();
        setField = new javax.swing.JTextField();
        savePathLabel = new javax.swing.JLabel();
        setLabel = new javax.swing.JLabel();
        openPathLabel = new javax.swing.JLabel();
        infoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wireworld");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(52, 73, 94));
        setForeground(java.awt.Color.blue);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);

        menuPanel.setBackground(new java.awt.Color(44, 62, 80));
        menuPanel.setToolTipText("");

        titleLabel.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(230, 126, 34));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Wireworld project");

        saveButton.setBackground(new java.awt.Color(52, 73, 94));
        saveButton.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(230, 126, 34));
        saveButton.setText("Save File");
        saveButton.setPreferredSize(new java.awt.Dimension(90, 25));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        setButton.setBackground(new java.awt.Color(52, 73, 94));
        setButton.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        setButton.setForeground(new java.awt.Color(230, 126, 34));
        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        openButton.setBackground(new java.awt.Color(52, 73, 94));
        openButton.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        openButton.setForeground(new java.awt.Color(230, 126, 34));
        openButton.setText("Open File");
        openButton.setPreferredSize(new java.awt.Dimension(90, 25));
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        startButton.setBackground(new java.awt.Color(230, 126, 34));
        startButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        startButton.setForeground(new java.awt.Color(52, 73, 94));
        startButton.setText("Start !");

        openPathField.setEditable(false);
        openPathField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openPathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPathFieldActionPerformed(evt);
            }
        });

        savePathField.setEditable(false);
        savePathField.setToolTipText("");
        savePathField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        setField.setText("Type here ...");
        setField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setFieldMouseClicked(evt);
            }
        });
        setField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFieldActionPerformed(evt);
            }
        });

        savePathLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        savePathLabel.setForeground(new java.awt.Color(240, 240, 240));
        savePathLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savePathLabel.setText("Save path");

        setLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        setLabel.setForeground(new java.awt.Color(240, 240, 240));
        setLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setLabel.setText("Number of Iterations");

        openPathLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        openPathLabel.setForeground(new java.awt.Color(240, 240, 240));
        openPathLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        openPathLabel.setText("Open path");

        infoButton.setBackground(new java.awt.Color(149, 165, 166));
        infoButton.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        infoButton.setText("Help");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(openPathField)
                                        .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(openPathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(savePathField)
                                        .addComponent(savePathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(setField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(setButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(setLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                                .addContainerGap(25, Short.MAX_VALUE))
                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(infoButton)
                                                .addContainerGap())))
        );
        menuPanelLayout.setVerticalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(titleLabel)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                                .addComponent(openPathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(setLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(savePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(openPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(savePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(setField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("Open");
        JFileChooser chooseFile = new JFileChooser();

        int result = chooseFile.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooseFile.getSelectedFile();
            filename = file.getAbsolutePath();
            openPathField.setText(filename);
            //  openPathField.setToolTipText(filename);
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Cancel was selected");
        }

    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("Save");
        JFileChooser saveFile = new JFileChooser();
        saveFile.setDialogTitle("Choose directory");
        saveFile.setCurrentDirectory(new java.io.File("."));
        saveFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = saveFile.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = saveFile.getCurrentDirectory();
            savename = file.getAbsolutePath();
            savePathField.setText(savename);
            //  openPathField.setToolTipText(filename);
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Cancel was selected");
        }
    }

    private void openPathFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void setFieldMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        setField.setText("");
    }

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //  System.out.println(setField.getText());
        if(setField.getText().equals(""))
        {
            System.out.println("pusto");
        }
        else if (setField.getText().equals("Type here ...")) {
            System.out.println("pusto");
        }
        else
        {

            setIterations = Integer.parseInt(setField.getText());
            System.out.println(setIterations);
        }
    }

    private void setFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu frame = new Menu();
                frame.setVisible(true);


            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton infoButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton openButton;
    private javax.swing.JTextField openPathField;
    private javax.swing.JLabel openPathLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField savePathField;
    private javax.swing.JLabel savePathLabel;
    private javax.swing.JButton setButton;
    private javax.swing.JTextField setField;
    private javax.swing.JLabel setLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration
}
