/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    String filename = null;
    String savename = null;
    int setIterations = -1;

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        openPathField = new javax.swing.JTextField();
        savePathField = new javax.swing.JTextField();
        setField = new javax.swing.JTextField();
        savePathLabel = new javax.swing.JLabel();
        setLabel = new javax.swing.JLabel();
        openPathLabel = new javax.swing.JLabel();
        infoButton = new javax.swing.JButton();
        openSuccess = new javax.swing.JLabel();
        saveSuccess = new javax.swing.JLabel();
        setSuccess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wireworld");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(52, 73, 94));
        setForeground(java.awt.Color.blue);
        setResizable(false);

        menuPanel.setBackground(new java.awt.Color(44, 62, 80));
        menuPanel.setToolTipText("");

        titleLabel.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(230, 126, 34));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Wireworld project");

        saveButton.setBackground(new java.awt.Color(52, 73, 94));
        saveButton.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(230, 126, 34));
        saveButton.setText("Save File");
        saveButton.setPreferredSize(new java.awt.Dimension(90, 25));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        setButton.setBackground(new java.awt.Color(52, 73, 94));
        setButton.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        setButton.setForeground(new java.awt.Color(230, 126, 34));
        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        openButton.setBackground(new java.awt.Color(52, 73, 94));
        openButton.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        openButton.setForeground(new java.awt.Color(230, 126, 34));
        openButton.setText("Open File");
        openButton.setPreferredSize(new java.awt.Dimension(90, 25));
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        startButton.setBackground(new java.awt.Color(230, 126, 34));
        startButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        startButton.setForeground(new java.awt.Color(52, 73, 94));
        startButton.setText("Start !");

        openPathField.setEditable(false);
        openPathField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openPathField.setMaximumSize(new java.awt.Dimension(120, 20));
        openPathField.setMinimumSize(new java.awt.Dimension(120, 20));
        openPathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPathFieldActionPerformed(evt);
            }
        });

        savePathField.setEditable(false);
        savePathField.setToolTipText("");
        savePathField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        savePathField.setMaximumSize(new java.awt.Dimension(125, 20));
        savePathField.setMinimumSize(new java.awt.Dimension(125, 20));
        savePathField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                savePathFieldMouseEntered(evt);
            }
        });

        setField.setText("Type here ...");
        setField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setFieldMouseClicked(evt);
            }
        });
        setField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFieldActionPerformed(evt);
            }
        });

        savePathLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        savePathLabel.setForeground(new java.awt.Color(240, 240, 240));
        savePathLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savePathLabel.setText("Save path");

        setLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        setLabel.setForeground(new java.awt.Color(240, 240, 240));
        setLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setLabel.setText("Number of Iterations");

        openPathLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        openPathLabel.setForeground(new java.awt.Color(240, 240, 240));
        openPathLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        openPathLabel.setText("Open path");

        infoButton.setBackground(new java.awt.Color(149, 165, 166));
        infoButton.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        infoButton.setText("Help");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        openSuccess.setForeground(new java.awt.Color(0, 204, 51));
        openSuccess.setText("  ");

        saveSuccess.setForeground(new java.awt.Color(0, 204, 51));
        saveSuccess.setText("  ");

        setSuccess.setForeground(new java.awt.Color(0, 204, 51));
        setSuccess.setText("   ");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(openPathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(openPathField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(openSuccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(8, 8, 8)
                                                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(savePathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(savePathField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                                .addGap(123, 123, 123)
                                                                .addComponent(infoButton))
                                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(setField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                                                                .addComponent(saveSuccess)
                                                                                .addGap(14, 14, 14)
                                                                                .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(setLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(setSuccess)))))
                                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(titleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(setLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(savePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(openPathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(openPathField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(setField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(savePathField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(setSuccess)
                                        .addComponent(saveSuccess)
                                        .addComponent(openSuccess))
                                .addGap(22, 22, 22)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("Open");
        openSuccess.setText("  ");
        JFileChooser chooseFile = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text files", "txt");
        chooseFile.setAcceptAllFileFilterUsed(false);
        chooseFile.setFileFilter(filter);
        int result = chooseFile.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooseFile.getSelectedFile();
            filename = file.getAbsolutePath();
            openPathField.setText(filename);
            openSuccess.setText("✓");
            //  openPathField.setToolTipText(filename);
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Cancel was selected");
        }

    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("Save");
        saveSuccess.setText("  ");
        JFileChooser saveFile = new JFileChooser();
        saveFile.setDialogTitle("Choose directory");
        saveFile.setCurrentDirectory(new java.io.File("."));
        saveFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = saveFile.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = saveFile.getCurrentDirectory();
            savename = file.getAbsolutePath();
            savePathField.setText(savename);
            saveSuccess.setText("✓");
            //  openPathField.setToolTipText(filename);
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Cancel was selected");
        }
    }

    private void openPathFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void setFieldMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        setField.setText("");
    }

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //  System.out.println(setField.getText());
        ErrorForm error = new ErrorForm();

        setSuccess.setText("  ");
        if(setField.getText().equals(""))
        {
            System.out.println("pusto");
            error.NewScreen("Iteration field is empty");

        }
        else if (setField.getText().equals("Type here ...")) {

            System.out.println("pusto");
            error.NewScreen("Iteration field is empty");
        }
        else if(isNumeric(setField.getText()) == false)
        {
            System.out.println("String or Double");
            error.NewScreen("Insertion is not integer");

        }
        else
        {
            setIterations = Integer.parseInt(setField.getText());
            setSuccess.setText("✓");
            System.out.println(setIterations);
        }

    }

    private void setFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        HelpForm help = new HelpForm();
        help.newScreen();

    }

    private void savePathFieldMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */

    private static boolean isNumeric(String str)
    {
        boolean numeric = true;

        try
        {
            int num = Integer.parseInt(str);
        } catch (NumberFormatException e)
        {
            numeric = false;
        }
        return numeric;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu frame = new Menu();
                frame.setVisible(true);



            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton infoButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton openButton;
    private javax.swing.JTextField openPathField;
    private javax.swing.JLabel openPathLabel;
    private javax.swing.JLabel openSuccess;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField savePathField;
    private javax.swing.JLabel savePathLabel;
    private javax.swing.JLabel saveSuccess;
    private javax.swing.JButton setButton;
    private javax.swing.JTextField setField;
    private javax.swing.JLabel setLabel;
    private javax.swing.JLabel setSuccess;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration
}
